@echo off
echo Starting ngrok...
start /B ngrok http --url=civil-duck-absolutely.ngrok-free.app 80
timeout /t 5 /nobreak
echo Starting Node.js app...
start cmd /k "cd /d D:\Documents\GithubRepos\PosterAssistant\backend\api && node app.js"
